version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: flaxtter
      POSTGRES_PASSWORD: "yBfDlAEIbsZXPZI25ANcEbdas9jsD4l_"
    volumes:
      - flaxtter_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "zFJF8Y7u0lR5h-Uvgj4870JwGbIRiggK"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  flaxtter_data:
